### PR TITLE
Allow to specify a type for foreign key column in migrations

### PR DESCRIPTION
**Pull request by tenderlove**
[Andrey Novikov & Łukasz Sarnacki]

This is a backport commit from master to support types in references calls in migrations.

### CODE REVIEW

**Comment by jrafanie** [comment]
:+1: Looks good to me.  Yay!

@Fryguy Care to merge if all good for you?

**Comment by Fryguy** [comment]
Merged.  @jrafanie Did you want to cut a tag for ManageIQ/manageiq#895 or should we just wait.

**Comment by jrafanie** [comment]
It's up to @tenderlove, if there's another commit on our rails fork coming soon, we can wait.  If not, then we can tag and update ManageIQ/manageiq#895 to have the bumping of the rails tag in the Gemfiles.

**Comment by tenderlove** [comment]
@jrafanie it's going to take me a little longer to get the PK integration working (probably early next week).  It's really up to you. ¯_(ツ)_/¯

**Comment by jrafanie** [comment]
Ok, I'll tag and update ManageIQ/manageiq#895 with the new rails tag.

**Pull request merged**
