### PR TITLE
remove truncate since it is in upstream.

### PR DESCRIPTION
**Pull request by tenderlove**
Fixed in rails in 9a4e183fe9f81365f7815c391512b3d46622d8c8

### CODE REVIEW

**Comment by Fryguy** [comment]
Would it make more sense to have this be a revert commit of  902525862f3c6040d08caee849ed6a9e68a9b8c7 ?  Then, like you said in ManageIQ/manageiq#721, backport AR:Base change into the initializer?  I don't even think we use the AR:Base change, so maybe we toss it altogether.

**Comment by tenderlove** [comment]
@Fryguy yep, a revert would be better.  I didn't submit a revert because my other PR didn't include the `truncate` method on Relation.  How about I include that, then we can do a revert instead?

**Comment by jrafanie** [comment]
@tenderlove Yeah, I agree with reverting it too :scissors:

**Comment by Fryguy** [comment]
@tenderlove Yup sounds good to me.

**Comment by tenderlove** [comment]
I've updated this PR to be a revert.

**Pull request merged**
