### PR TITLE
Not treating serialized field changes differently than other fields

### PR DESCRIPTION
**Pull request by kbrock**
Working on getting a better change upstream into rails (active_record)

This only saves fields to the database that are marked as changed via: `field_will_change!` or `field=new_value`

NOTE:
Bundler isn't able to find arel 3.0.2 so I'm not able to run the tests.

ALSO:
I'm not sure if I have the pull request off of the correct branch. please double check this.

### CODE REVIEW

**Comment by Fryguy** [comment]
This change kind of scares me because I know we have places in the code where we do things like modify the  unserialized hash directly, and the changes would no longer be written.

Not to mention I generally dislike putting the onus of remembering things on a developer.

**Comment by kbrock** [comment]
@Fryguy is this better?

I copied `keys_for_partial_write` from rails 4.x/`master`. I did not introduce any other change from `master`, and this should not change any behavior.

This allows us to introduce:

``` ruby
module DontAutoSaveSerialized
  extend ActiveSupport::Concern

  def should_record_timestamps?
    self.record_timestamps && (!partial_updates? || changed?)
  end

  def update(*)
    if partial_updates?
      super(changed)
    else
      super
    end
  end
end
```

And more importantly:

``` ruby
class MiqQueue
  include_concern "DontAutoSaveSerialized"
end
```

/cc @jrafanie (I've got multiple horses on the track for solving this one. And even if we get our change into rails proper, it will take a while to get 4.1 into our code base)

**Comment by jrafanie** [comment]
Same as referenced cfme pull:  @kbrock We need a way to detect when this monkey patch is no longer needed.  In other words, when we finally upgrade to a version of Rails where this is magically fixed, the monkey patch should YELL and complain that it's no longer needed.  If that's not possible, does it make sense to wait until we can get someone on Rails core to bite on merging a solution so we can craft a temporary monkey patch that allows us to raise an exception if you try to run this patch against the NEXT_RAILS_VERSION_HAVING_THIS_FIX?

**Comment by kbrock** [comment]
This fix takes the code closer to rails 4.x.
So I don't really consider this a monkey patch.

**Comment by jrafanie** [comment]
Let's discuss this with @Fryguy as I need to take a step back and
understand what our strategy is short term (this pull) and long term.  The
idea is to get it merged upstream if we have to tweet everyone in the world
;-)  Then backport the easiest fix that will work in our current codebase
with some "self deprecating behavior" (pun was intentional), so we know
when it's no longer needed.  I think we're close on the latter but want all
of us on the same page.

**Comment by kbrock** [comment]
We want a switch: `dont_save_all_serialized_attributes`

We get the same behavior whether rails gives us the switch, or we patch some methods. (as long as the patch can be applied in `config/initializers` or `include ModuleX`.

Either mechanism could brake once rails decides to significantly upgrades active record, but a built in rails switch has more chance of continuing to work.

The most probable breakage of our patch is `keys_for_partial_write` no longer being called.

I'm in favor of anything that gets us closer to a rubygems version of rails.

**Pull request merged**
