### PR TITLE
measure record instantiation time in AS::Notifications

### PR DESCRIPTION
**Pull request by tenderlove**
emit an event when we instantiate AR objects so we can see how manyrecords were instantiated and how long it took

backport of rails/rails@2a0d97bc89fc230241453cbbf55621309e1f3ac6

### CODE REVIEW

**Comment by jrafanie** [comment]
:heart:

**Comment by jrafanie** [comment]
@tenderlove I get the following error locally:

```
bin/rails c

irb(main):012:0> Vm.includes(:hardware).where("hardwares.vm_or_template_id IS NOT NULL").all

NoMethodError: undefined method `base_klass' for #<ActiveRecord::Associations::JoinDependency::JoinBase:0x007fc95cdb1c30>
    from /Users/joerafaniello/.gem/ruby/1.9.3/bundler/gems/rails-d6f98379885b/activerecord/lib/active_record/associations/join_dependency.rb:56:in `instantiate'
    from /Users/joerafaniello/.gem/ruby/1.9.3/bundler/gems/rails-d6f98379885b/activerecord/lib/active_record/relation/finder_methods.rb:213:in `find_with_associations'
    from /Users/joerafaniello/Code/manageiq/vmdb/lib/extensions/ar_virtual.rb:320:in `find_with_associations_with_virtual'
    from /Users/joerafaniello/.gem/ruby/1.9.3/bundler/gems/rails-d6f98379885b/activerecord/lib/active_record/relation.rb:171:in `exec_queries'
    from /Users/joerafaniello/.gem/ruby/1.9.3/bundler/gems/rails-d6f98379885b/activerecord/lib/active_record/relation.rb:160:in `block in to_a'
    from /Users/joerafaniello/.gem/ruby/1.9.3/bundler/gems/rails-d6f98379885b/activerecord/lib/active_record/explain.rb:40:in `logging_query_plan'
    from /Users/joerafaniello/.gem/ruby/1.9.3/bundler/gems/rails-d6f98379885b/activerecord/lib/active_record/relation.rb:159:in `to_a'
    from /Users/joerafaniello/.gem/ruby/1.9.3/bundler/gems/rails-d6f98379885b/activerecord/lib/active_record/relation.rb:189:in `exec_queries'
    from /Users/joerafaniello/.gem/ruby/1.9.3/bundler/gems/rails-d6f98379885b/activerecord/lib/active_record/relation.rb:160:in `block in to_a'
    from /Users/joerafaniello/.gem/ruby/1.9.3/bundler/gems/rails-d6f98379885b/activerecord/lib/active_record/explain.rb:33:in `logging_query_plan'
    from /Users/joerafaniello/.gem/ruby/1.9.3/bundler/gems/rails-d6f98379885b/activerecord/lib/active_record/relation.rb:159:in `to_a'
    from /Users/joerafaniello/.gem/ruby/1.9.3/bundler/gems/rails-d6f98379885b/activerecord/lib/active_record/relation/finder_methods.rb:159:in `all'
    from (irb):12
```

It looks like base_klass was added to join_dependency after 3.2.x:
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/associations/join_dependency.rb#L48

Here: d87966c1c4119dbfa0808d7bd477b59a6b5f232c

**Comment by tenderlove** [comment]
Argh. I ran the tests too :'(

**Comment by jrafanie** [comment]
I'm the guy who merged it without verifying it so it's my fault too... :hear_no_evil:  

So, I hear you want us on edge rails?

**Pull request merged**
